A little bit more complex getget script

diff --git a/2step b/2step
--- a/2step
+++ b/2step
@@ -1,27 +1,34 @@
 #!/bin/bash
 # https://youtu.be/RuLSZkWwlC4
 # https://github.com/quarkscript/batch-install-scripts
-./getget 
-mkinitcpio -p linux >> /install.log
-grub-mkconfig -o /boot/grub/grub.cfg >> /install.log 
-echo
+if [ ! -e "getget" ]&&[ -e "getget_old" ]; then
+    ./getget_old
+elif [ -e "getget" ]; then
+    ./getget |& tee -a /install.log
+else
+    echo 'Error: missing "getget" or "getget_old"'
+    exit 1
+fi
+mkinitcpio -p linux  |& tee -a /install.log
+grub-mkconfig -o /boot/grub/grub.cfg  |& tee -a /install.log
 
-echo "Fast reinstall instruction: (if needed)"
-echo "- exit from arch-chroot"
-echo "- execute mc and remove all folders from /mnt except /var/cache/pacman/pkg"
-echo "- remove wrong/unneeded packages from /mnt/pacmanlist.txt"
-echo "- exit from mc and repeat /mnt/1step"
+echo "
+Fast reinstall instruction: (if needed)
+- exit from arch-chroot
+- execute mc and remove all folders from /mnt except /var/cache/pacman/pkg
+- remove wrong/unneeded packages from /mnt/pacmanlist.txt
+- exit from mc and repeat /mnt/1step
+" |& tee -a /install.log
 
 if [ -e ignored.txt ]
     then
-    echo
-    echo packages unavailable from repository:
-    echo $(cat ignored.txt)
-    echo You can install alternatives manually or try without them
+    echo "packages unavailable from repository:" |& tee -a /install.log
+    echo "$(cat ignored.txt)" |& tee -a /install.log
+    echo "You can install alternatives manually or try without them" |& tee -a /install.log
 fi
 
-echo
-echo  "before reboot do not forget"
-echo  "to install bootloader like"
-echo  "grub-install /dev/sdX"
-echo 
+echo '
+before reboot do not forget
+to install bootloader like
+grub-install /dev/sdX
+'  |& tee -a /install.log
